// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuGKfTTMBfXBhQahHH_iOaUrKM2QH8-Pc',
    appId: '1:774660161251:android:5dce3f8026152b53c54fd6',
    messagingSenderId: '774660161251',
    projectId: 'wawatair-b212f',
    storageBucket: 'wawatair-b212f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBasfE3lO9CmC1wlezgcPeq-iTceSIrh74',
    appId: '1:774660161251:ios:2574ee0dd4387474c54fd6',
    messagingSenderId: '774660161251',
    projectId: 'wawatair-b212f',
    storageBucket: 'wawatair-b212f.firebasestorage.app',
    iosBundleId: 'wawat.land',
  );

}